### ISSUE TITLE
Create filters/plugins for some communicators

### ISSUE THREAD

**Issue by rakiop** [rakiop/agh-odis-proxy#17]

**Comment by kporzycki** [comment]
I've solved it for XMPP, Yahoo Messenger and IRC by using SocketConnectionLogger. It only blocks the connections now, though. Can we log the connection and still keep it open and functioning as proxy?

**Comment by rakiop** [comment]
Nope. We could do this if we know end host for this connection but if we do not than this connection ends on us. But that was requirement from him so :)
